default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: circle_ruby_dev

test:
  <<: *default
  database: circle_ruby_test<%= ENV['CIRCLE_NODE_INDEX'] %>
